# default


[Camera Detail]
# 'on' (default) | 'off'  | 'split' --- luồng âm thanh khi xem liveview của 1 camera
livewiew_detail_audio_source = on

[Window]
# maximum number of sub-windows (default: 10)
maximum_sub_windows = 3