syntax = "proto3";
import "comm.model.proto";
package comm;
//option optimize_for = LITE_RUNTIME;
//ID: [100-129]
//receive: [4-9]
option java_package = "com.vivas.ipcamera.core.protobuf";
message ReceiveProfile
{
	uint32 type = 1;
	Profile profile = 2;
	enum Type
	{
		UPDATE = 0;
		KICK = 1;
	}
	uint32 RECEIVE_PROFILE = 4;
}

message KeepAlive
{
	message Request
	{
		bool idle = 1;
	}
	message Reply
	{
	}
	uint32 ID = 100;
}

message Authenticate //HTTP
{
	message Request
	{
		string account = 1;// using phone or email
		string password = 2;
		uint32 platform = 3;
		string token = 4;
		string app_version = 5;
	}
	message Reply
	{
		bytes uid = 1;
		bytes session_id = 2;
		string host = 3;
		uint32 port = 4;
		string webSock_host = 5;
		uint32 webSock_port = 6;
		string ssid = 7; // string session_id
		License_profile license_profile = 8;
		bool web_socket_tls_enable = 9;
	}
	enum Error
	{
		ERROR_DEFAULT = 0;
		ACCOUNT_INVALID = 1;
		PASSWORD_INVALID = 2;
		PLATFORM_INVALID = 3;
		TOKEN_INVALID = 4;
		ACCOUNT_NOT_ACTIVE = 5;
		LICENSE_EXPIRED = 6;
	}
	uint32 ID = 101;
}

message Login
{
	message Request
	{
		bytes uid = 1;
		bytes session_id = 2;
		ProjectTarget target = 3; /// cho dự án nào // lấy trong enum ProjectTarget của comm.model
		int32 apiVersion = 4; /// lấy ở trong enum API trong comm.model
        uint32 platform =5 ;
	}
	message Reply
	{
		TurnAccount turn_account = 1;
		uint64 server_time = 2;
		Profile profile = 3;
		uint32 server_version_build = 4;
		string base_image_url = 5;
		repeated string list_ntp_server = 6;
        uint32 build_number = 7 ;
        string link_download = 8;
		ProjectTarget target = 9; /// cho dự án nào // enum ProjectTarget {VIVAS = 0;VIVAS_CLOUD = 1;KC01 = 99;}
		BaseURL base_url = 10; // List base url config
		License_profile license_profile = 11;
	}

	message BaseURL{
	    string face_base_url = 1;// Base url face detection
	}

	enum Error
	{
		ERROR_DEFAULT = 0;
		SESSION_EXPIRED = 1;
		USER_INVALID = 2;
		VERST_IION_API_DEPRECATED = 3;
		PROJECT_TARGENVALID = 4;
		LICENSE_EXPIRED = 6;
	}
	uint32 ID = 102;
}

message Logout
{
	message Request{}
	message Reply{}
	uint32 ID = 103;
}

/************** Register And active account *******************/

message Register //HTTP
{
	message Request
	{
		string account = 1; // gửi email hoặc số điện thoại như cũ
		string password = 2;
		string otp = 3;
		string address = 4;
		string email = 5; /// trường account trên desktop có thể login bằng trường này
		string tel = 6; /// trường account trên desktop có thể login bằng trường này

	}
	message Reply
	{
	}
	enum Error
	{
		ERROR_DEFAULT = 0;
		ACCOUNT_EXIST = 1;
		OTP_NOT_MATCH = 2;
		OTP_EXPIRED = 3;
		EMAIL_INVALID = 4;
		TEL_INVALID = 5;
		PASSWORD_INVALID = 6;
		ACCOUNT_INVALID = 7;
		PASSWORD_CONTAINING_SPECIAL_CHARACTERS = 8;
		PASSWORD_WEAKNESS = 9;
	}
	uint32 ID = 104;
}

message UpdateDeviceToken
{
	message Request
	{
		string token = 1;
	}
	message Reply
	{
	}
	uint32 ID = 105;
}

message ChangePassword
{
	message Request
	{
		string current = 1;
		string password = 2;
		bool kick_others = 3;
	}
	message Reply
	{
	}
	enum Error
	{
		ERROR_DEFAULT = 0;
		PASSWORD_INVALID = 1;
		PASSWORD_WEAKNESS = 2;
		PASSWORD_NOT_SAME = 3;
	}
	uint32 ID = 106;
}
message ForgotPassword
{
	message Request
	{
		string account = 1;
		string password = 2;
		string otp = 3;
		bool kick_out = 4;
	}
	message Reply
	{
	}
	enum Error
	{
		ERROR_DEFAULT = 0;
		PASSWORD_INVALID = 1;
		OTP_NOT_MATCH = 2;
		OTP_EXPIRED = 3;
		TEL_INVALID = 4;
		EMAIL_INVALID = 5;
		PASSWORD_OTP_INVALID = 6;
		ACCOUNT_INVALID = 7;
		PASSWORD_CONTAINING_SPECIAL_CHARACTERS = 8;
		PASSWORD_WEAKNESS = 9;
	}
	uint32 ID = 107;
}

message RequestOTP  //HTTP
{
	message Request
	{
		string account = 1;
	}

	message Reply
	{
		uint32 wait_time = 1;
	}

	enum Error
	{
		ERROR_DEFAULT = 0;
		TEL_INVALID = 1;
		EMAIL_INVALID = 2;
		ALREADY_GET_OTP = 3;
		EXCEEDED_TIMES_GET_OTP = 4;
		ACCOUNT_INVALID = 5;

	}
	int32 ID = 108;
}

message CheckAccount //HTTP
{
	enum State { NOT_EXISTED = 0; TEL_EXISTS = 1; EMAIL_EXISTS = 2; }
	message Request
	{
		string account = 1;
		string password = 2;
	}
	message Reply
	{
		State state = 1;
	}
	enum Error
	{
		ERROR_DEFAULT = 0;
		TEL_INVALID = 1;
		EMAIL_INVALID = 2;
		TEL_ALREADY_IN_USE = 3;
		EMAIL_ALREADY_IN_USE = 4;
		ACCOUNT_INVALID = 5;
		PASSWORD_INVALID = 6;
		PASSWORD_EMPTY = 7;
		PASSWORD_CONTAINING_SPECIAL_CHARACTERS = 8;
		PASSWORD_WEAKNESS = 9;
	}
	int32 ID = 109;
}

message FeedbackUser
{
	message Request
	{
		string feedback = 1;
	}
	message Reply
	{

	}
	enum Error
	{
		ERROR_DEFAULT = 0;
		FEEDBACK_EMPTY = 1;
	}
	int32 ID = 110;
}

message CheckAccountExists
{
	message Request
	{
		string account = 1;
	}
	message Reply
	{
		bool isExists = 1;
		string info = 2;
	}
	enum Error
	{
		ERROR_DEFAULT = 0;
		TEL_INVALID = 1;
		EMAIL_INVALID = 2;
		TEL_NOT_IN_USE = 3;
		EMAIL_NOT_IN_USE = 4;
		ACCOUNT_INVALID = 5;
	}
	int32 ID = 111;
}
/* Nếu status = 0 và wait_time thì tài khoản vẫn trong thời gian get otp của phiên trước */

message RequestUpdateTelProfile
{
	message Request
	{
		string tel = 1;
		string current_password = 2;
	}
	message Reply
	{
		uint32 wait_time = 1;
	}
	enum Error
	{
		ERROR_DEFAULT = 0;
		PASSWORD_NOT_MATCH = 1;
		TEL_INVALID = 2;
		TEL_EXIST = 3;
		SYN_ERROR = 4;// Lỗi đồng bộ vs ONESME
	}
	int32 ID = 112;
}
message UpdateTelProfile
{
	message Request
	{
		string otp = 2;
	}
	message Reply
	{
		Profile newProfile = 1;
	}
	enum Error
	{
		ERROR_DEFAULT = 0;
		OTP_EMPTY = 1;
		OTP_NOT_MATCH = 2;
		OPT_EXPIRED = 3;
		OPT_NOT_FOUND = 4;
		TEL_EXIST = 5;
		SYN_ERROR = 6;// Lỗi đồng bộ vs ONESME
	}
	int32 ID = 113;
}
/* Nếu status = 0 và wait_time thì tài khoản vẫn trong thời gian get otp của phiên trước */
message RequestUpdateEmailProfile
{
	message Request
	{
		string email = 1;
		string current_password = 2;
	}
	message Reply
	{
		uint32 wait_time = 1;
	}
	enum Error
	{
		ERROR_DEFAULT = 0;
		PASSWORD_NOT_MATCH = 1;
		EMAIL_INVALID = 2;
		EMAIL_EXIST = 3;
		SYN_ERROR = 4;// Lỗi đồng bộ vs ONESME
	}
	int32 ID = 114;
}
message UpdateEmailProfile
{
	message Request
	{
		string otp = 2;
	}
	message Reply
	{
		Profile newProfile = 1;
	}
	enum Error
	{
		ERROR_DEFAULT = 0;
		OTP_EMPTY = 1;
		OTP_NOT_MATCH = 2;
		OPT_EXPIRED = 3;
		OPT_NOT_FOUND = 4;
		EMAIL_EXIST = 5;
		SYN_ERROR = 6;// Lỗi đồng bộ vs ONESME
	}
	int32 ID = 115;
}
message CloudDefaultSetting
{
	message Request
	{
		bool power_cloud_storage = 1; // ON-OFF
		uint32 number_days_storage = 2; // 7 15 30 or custom
	}
	message Reply
	{
		Profile newProfile = 1;
	}
	enum Error
	{
		ERROR_DEFAULT = 0;
	}
	int32 ID = 116;
}

message VerifyURL
{
    message Request
    	{
    		string url = 1; //server base url
    	}
    	message Reply
    	{
    		License_profile license_profile = 1;
    	}
    	enum Error
    	{
    		ERROR_DEFAULT = 0;
    		URL_INVALID = 1;
    	}
    	int32 ID = 117;
}

message VconnexLogin
{
	message Request
	{
		string token = 2;
		ProjectTarget target = 3; /// cho dự án nào // lấy trong enum ProjectTarget của comm.model
		int32 apiVersion = 4; /// lấy ở trong enum API trong comm.model
		uint32 platform =5 ;
	}
	message Reply
	{
		TurnAccount turn_account = 1;
		uint64 server_time = 2;
		Profile profile = 3;
		uint32 server_version_build = 4;
		string base_image_url = 5;
		repeated string list_ntp_server = 6;
		uint32 build_number = 7 ;
		string link_download = 8;
		ProjectTarget target = 9; /// cho dự án nào // enum ProjectTarget {VIVAS = 0;VIVAS_CLOUD = 1;KC01 = 99;}
		BaseURL base_url = 10; // List base url config
		License_profile license_profile = 11;
	}

	message BaseURL{
		string face_base_url = 1;// Base url face detection
	}

	enum Error
	{
		ERROR_DEFAULT = 0;
		SESSION_EXPIRED = 1;
		USER_INVALID = 2;
		VERST_IION_API_DEPRECATED = 3;
		PROJECT_TARGENVALID = 4;
		LICENSE_EXPIRED = 6;
	}
	uint32 ID = 118;
}

message RemoveAccount
{
	message Request
	{
	}
	message Reply
	{
	}
	enum Error
	{
		ERROR_DEFAULT = 0;
	}
	int32 ID = 119;
}