syntax = "proto3";
import "comm.model.proto";
package comm;
//option optimize_for = LITE_RUNTIME;
//ID: [100-129]
//receive: [4-9]
option java_package = "com.vivas.ipcamera.core.protobuf";
message ReceiveProfile
{
	uint32 type = 1;
	Profile profile = 2;
	enum Type
	{
		UPDATE = 0;
		KICK = 1;
	}
	uint32 RECEIVE_PROFILE = 4;
}

message KeepAlive
{
	message Request
	{
		bool idle = 1;
	}
	message Reply
	{
	}
	uint32 ID = 100;
}

message Authenticate //HTTP
{
	message Request
	{
		string account = 1;// using phone or email
		string password = 2;
		uint32 platform = 3;
		string token = 4;
		string app_version = 5;
	}
	message Reply
	{
		bytes uid = 1;
		bytes session_id = 2;
		string host = 3;
		uint32 port = 4;
		string webSock_host = 5;
		uint32 webSock_port = 6;
		string ssid = 7; // string session_id
		License_profile license_profile = 8;
		bool web_socket_tls_enable = 9;
	}
	enum Error
	{
		ERROR_DEFAULT = 0;
		ACCOUNT_INVALID = 1;
		PASSWORD_INVALID = 2;
		PLATFORM_INVALID = 3;
		TOKEN_INVALID = 4;
		ACCOUNT_NOT_ACTIVE = 5;
		LICENSE_EXPIRED = 6;
	}
	uint32 ID = 101;
}

message Login
{
	message Request
	{
		string uid = 1; // Lấy từ api authen mới  
		string session_id = 2; // lấy từ api authen mới
	}
	message Reply
	{
		uint64 server_time = 1;
		Profile profile = 2;
		string base_api_url = 3;
	}
	enum Error
	{
		ERROR_DEFAULT = 0;
		SESSION_EXPIRED = 1;
		USER_INVALID = 2;
		VERST_IION_API_DEPRECATED = 3;
		PROJECT_TARGENVALID = 4;
		LICENSE_EXPIRED = 6;
	}
	uint32 ID = 102;
}